sudo: false
cache:
  bundler: true
  directories:
  - cache/
notifications:
  email: false
language: c
compiler: gcc
env:
  global:
  - PACKAGE=helloworld
  - USER=osdu
  - REPO=openwrt-helloworld
  - secure: "YLxUjhv8OxsKKoY9qcblZQSRKlRnHyzV2GoHtKvEgS7fISaS1D46ycUuozNjTbfCKyEDnsri2xqGtwj/jZoMhWbJKYC+xld5QRivF0xoneflGVVm0WDMMliZBTn3flYDaWzPgZBwy7gDpFgsCa7F8E1F8e86/yqesOJJwbg4WzGDE3Yf0+dPubhwGOZrXdZD5mf1Y6Et0k+qKF/3FyLw0K9dGV/5CC+6NJKn8geXErA1Ju51I6buHccRvgbgC7I7yyg0J+p6QUVPmjFEaK0Y5fDY/BQRo8OfE6T9g5myF/lRsvRhDxWTrQhhTWAHlUMT22D7kZ/WzxNGGak1c87B0QHeGX4MWd1N+bcq29dkDeREdKAjf1CT7EkKbQFw8Jwe4lAXbPrH160eyY33QsAEXpaTeQAcHqHcYkRAvmvbIDKYEIKjZtM0ARlPj/1c8aK1L7Fq30irUbswBUby3Q661w4oqXKnJ4pO3zrZ7Lw7oQTTKKj73u1tn1KRRg+DGdvmd2K6z9f5mN+UktLwmGoTrJfNRZZC6Ni9LtcPPBsPebVGJUindd4mrvzkqXrf5fIuSd0mwx/d4s2C2/cVFoDEFWlfsaQc/MbR5E7+5BgA1EkcXSM2lY4Fabby5RK7KG5yey3dgVkBjBxPb0LbuIQQhpx5c6CFA5H9D8PrvrlFnEM="
  matrix:
  - SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05/ar71xx/generic/OpenWrt-SDK-15.05-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
  - SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05/ramips/mt7620/OpenWrt-SDK-15.05-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
install:
- mkdir -p $TRAVIS_BUILD_DIR/local ; cd $TRAVIS_BUILD_DIR/local
- wget "http://us.archive.ubuntu.com/ubuntu/pool/main/c/ccache/ccache_3.1.6-1_amd64.deb"
- dpkg -x *.deb .
- mkdir -p $TRAVIS_BUILD_DIR/cache ; cd $TRAVIS_BUILD_DIR/cache
- wget -c $SDK_URL
- mkdir -p $TRAVIS_BUILD_DIR/sdk ; cd $TRAVIS_BUILD_DIR/sdk
- export FILE=$TRAVIS_BUILD_DIR/cache/$(basename $SDK_URL)
- file $FILE
- tar xjf $FILE
- cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*
- mkdir package/$PACKAGE
- ln -s $TRAVIS_BUILD_DIR/Makefile package/$PACKAGE/
- ln -s $TRAVIS_BUILD_DIR/src package/$PACKAGE/
script:
- export PATH=$TRAVIS_BUILD_DIR/local/usr/bin:$PATH
- cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*
- "./scripts/feeds update packages >/dev/null"
- make V=s
- find $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*/bin/
- find . -name *.ipk -exec cp {} $TRAVIS_BUILD_DIR \;
- cd $TRAVIS_BUILD_DIR/
- chmod a+x $TRAVIS_BUILD_DIR/deploy.sh
after_success: "$TRAVIS_BUILD_DIR/deploy.sh"
before_deploy: git fetch --tags
deploy:
  provider: releases
  api_key:
    secure: "thQIKtPSD0rv4ucsS0cbDiAWiBpjOhL8RDwOHwHGggD7QrGE4DrrLFz3GHVyG6Y8pnx+n95mt1SLnERzNJGXJveQ9kAmb+jqi+Fr+Af5H6VN9qpU5ldbzBjoCosk/JEjBsjUPEeFiHDiuRLISUK+afFm6nMgH8spLEw+oz+BUlohcDMdKq9T1U2TVpAvtvaFEROJJe8TkW7NklQdUylqbQv+iY8VF4lrvnzZZepTu7QN94uVGdero9RChtijZC+MGkTTvB7+3lOFvfFalyExd/ma2LHsvKeTEPciU9qwBP2W/E/IoWWZBHAqZdwpDCgusNz4ei/fH96A0f9VoLSUNfQChLTz7bPe7Poch/tjORDPM4QPLdcyaOLSgr0zQ6Nchp9ySS3JkrpgN2lEAhn61jqafI/HJs5Ir1gyOQ4fjUEr2JA+rlaolTLbIhjnMYf8a5gafAzsHlJpY2yArjM1nBxxAOZFmQGP0FjMM6Ir5J/wgv5RB50X5/wH0G9uZ03Ehs+rQmeRUzMumP7AJlb2RhIwmhZF22HtHCN+F3v8aC8gQMLTySzrGUUXjyUResRO0QT3vaHMwQVHHtSUdL2ZdOXtD5edUrMfqoSLLIV8O1HY0KYWGeHDi2o9kh5vUBjD8LBT9AJB/INwExcF6zIAvRi0B9v1URYbh7xXy26M2MA="
  skip_cleanup: true
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/*.ipk"
  on:
    tags: true
    all_branches: true
